# -*- coding: utf-8 -*-
"""Prueba_github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GByRiIsOWpphaVix3PLH0ji3FUmSDDP3
"""

import pandas as pd
import numpy as np

# Definimos el tamaño del DataFrame aleatorio
filas = 10
columnas = 5

# Creamos un DataFrame con valores aleatorios
df = pd.DataFrame(np.random.rand(filas, columnas), columns=['A', 'B', 'C', 'D', 'E'])

# Mostramos el DataFrame
print(df)

import matplotlib.pyplot as plt

# Graficar un scatter plot de dos columnas del DataFrame
plt.scatter(df['A'], df['B'])
plt.title('Gráfico de dispersión de columnas A y B')
plt.xlabel('Columna A')
plt.ylabel('Columna B')
plt.grid(True)
plt.show()

# Graficar un gráfico de líneas de las dos primeras filas del DataFrame
df.iloc[:2].plot(kind='line')
plt.title('Gráfico de líneas de las dos primeras filas')
plt.xlabel('Índice de fila')
plt.ylabel('Valores')
plt.grid(True)
plt.legend(loc='upper right')
plt.show()